name: Make index

# Convert README.ipynb to README.md via nbconvert on push.
on:
  push:
    branches: [ master ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - uses: actions/checkout@v2
      - name: Install Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      # Install nbconvert
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

        # Convert
      - name: Convert notebook
        run: jupyter nbconvert --ClearMetadataPreprocessor.enabled=True --ClearOutput.enabled=True  --to html main.ipynb

      # Commit.
      - name: Commit files
        run: |
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          rm docs/index.html
          mv main.html docs/index.html
          git add docs/index.html
          git commit -m "Convert README.ipynb to markdown" -a

      # Push to master
      - name: Push changes to master
        if: success()
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}